name: Check code=555 formatting

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install packages
      run: source tools/ci.sh && ci_code_formatting_setup
    - name: Run code=01 MyChatApp formatting
      run: source tools/ci.sh && ci_code_formatting_run
    - name: Check blab Ax code formatting
      run: git diff --exit-code
